---
title: "STA3041F 2026 Tutorial Assessment 3"
author: "Amara Patel (PTLAMA005) and Malik Jamie (JMXMAL003)"
date: '2026-03-27'
output: pdf_document
header-includes:
  - \usepackage{pdfpages}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stats)
```

## Question 1

```{r q1, fig.align='center',fig.width=5,fig.height=5, fig.cap='Figure caption here.'}
rm(list = ls())
dat = read.table("BatRun Data 2.txt", h = TRUE)

# Plot the count trajectory and place tick marks for the arrivals
plot(dat$Sn~dat$Pos, type='s', xlab = "Time in minutes from 03:30 hour mark", ylab = "Count", main = "Count Trajectory of BATRUN Race")

# the tick marks aren't working even though i used his hint so help pls
points(rep(0,length(dat$Sn))~dat$Sn, pch = "|", col = "pink")
#segments(dat$Sn, 0, dat$Sn, 0.5, col= "pink", lwd = 3)
```

## Question 2

\begin{equation*}
\begin{aligned}
\mbox{mvf}(v;\boldsymbol\beta) &= \int \lambda(u;\boldsymbol\beta)du\\
 &= \int_0^t \exp\left(-\beta_1^2\beta_2 + 2\beta_1\beta_2u - \beta_2u^2 \right)du\\
 &=\int_0^t \exp\left(-\beta_2 (u - \beta_1)^2 \right) du \\
 &\text{let s} = \sqrt{2\beta_2}(u-\beta_1) \text{ then:}\\
 &=\\
 &=\\ 
 &=K(\beta_2)\times\Phi\bigg(v;?,?\bigg)\\
\end{aligned}
\end{equation*}

## Question 3

```{r q3}

# fixed n mode (ie n=50, not looking at a fixed window)
mvf_1    = function(v,pars)
{
		beta = pars
		mvf <- ((1/(beta[2])) * exp(beta[1])) * (exp(beta[2]*v) - 1)
	  return(mvf)
}
min_likelihood_1 = function(pars)
{
	  beta  = pars
	  value =  
	  return(-value)
}

mvf_2    = function(v,pars)
{
	  beta  = 
	  K     = 
	  return()
}

min_likelihood_2 = function(pars)
{
	  beta  = 
	  value =  
	  return(-value)
}

```

## Question 4

```{r q4}
#res_opt_1 = nlm()
#res_opt_2 = nlm()
#M1  = c()#beta hat here, #AIC here
#M2  = c()#beta hat here, #AIC here
#tab = cbind(M1,M2)
#rownames(tab) = c('beta[1]','beta[2]','AIC')
#colnames(tab) = c('Model 1','Model 2')
#tab
```

## Question 5

```{r q5, fig.align='center',fig.width=5,fig.height=5}

#tt = 
#E1 = 
#E2 = 

```

## Question 6

```{r q6}
#forecast = 
#forecast
```

