---
title: "ED Assignment"
format: pdf
editor: visual
author: Malik Jamie (JMXMAL003) and Amara Patel (PTLAMA005)
date: 21/10/2025
---

# Introduction

The aim of this experiment is to examine the effects of different intensities of heat and light on the growth of chilli plants. The goal is to determine whether light and heat affect chilli growth, which settings produce the highest quality chillies and by how much. Furthermore, whether these settings depend on variety as well as whether quality depends on variety will be explored. This is to make recommendations about which heat and light settings are optimal for small-scale farmers to implement, taking into account the cost of additional heat and light.

These goals will be tackled through an analysis of variance of this exploratory experiment.

## Section 1: Design and Randomisation

###planning: factorial experiment: factor one: light level (1, 2, 3, 4) factor two: heat level (1, 2, 3, 4) factor three: variety of chilli (R, F) Number of treatments: 32 (light, heat, variety); (11R, 11F, 12R, 12F, 13R, 13F, 14R, 14F, 21R, 21F, 22R, 22F, 23R, 23F, 24R, 24F, 31R, 31F, 32R, 32F, 33R, 33F, 34R, 34F, 41R, 41F, 42R, 42F, 43R, 43F, 44R, 44F)

experimental unit: plots (only one treatment per plot); 32 plots over two greenhouses blocking factor 1: north/south blocking factor 2: greenhouse (A, B) blocking factor 3: season (1, 2)

note: it says each plot is large enough for several chilli plants. so perhaps each plot should have one of each variety of chilli, then we can repeat across north/south or across the two greenhouses to remove that variance

design idea: overarching block: season 1 and season 2 (randomise the 32 treatments to the 32 plots (16 treatments per greenhouse) blocking with season for greenhouse and side of the greenhouse so possible latin square design/nest the blocks)

then we can remove one of these two blocking factors above (ie overarching block: season; each treatment of heat and light (16 total) randomised to 32 plots (one in each greenhouse), with one of each type of chilli in each plot; then we block for north/south - in this case, experimental unit would be plants.

final design idea: - whole block: season - sub block: greenhouse-side block - randomise for variety across season block - randomise for light and heat across(16 combinations) across the greenhouses in a latin square design to block for location within the greenhouse (n-s, e-w)

hypotheses (i honestly don't know how i should be defining these... possibly using contrasts but not sure. also not sure how i should be setting up the model but i am busy doing more stats and reading to figure it all out): 1: Does light have an effect on the quality of chillies $H_0: \alpha_{light} = 0$ $H_1: \alpha_{light} \ne 0$

2: Which light setting has the biggest effect 2: Does heat have an effect on the quality of chillies

the code chunk below is basically just setting up a possible design where i've randomised variety over greenhouse-season blocks and then randomised light and heat within each greenhouse. not sure what this means for the analysis of the effects of variety (do experimental units for variety change from plot to greenhouse, w two reps or can we just analyse the 64 individual plots and make conclusions about those while adjusting for the greenhouse-season blocking factor?) i honestly don't know how this project is supposed to be approached and i feel a little bit lost to be honest. i might go to the lab session on tuesday and ask some of the tutors for advice.

i think it's best if we sit down together and fully decide what design and stuff we agree on and talk through it a lot more to make sure it makes sense to both of us and is also doable.

```{r Design and Randomisation}
# loading packages
library(tibble)
library(knitr)
library(dplyr)

# setting seed for reproducibility 
set.seed(8)

# factors: 
light <- as.factor(c(1, 2, 3, 4))
heat <- as.factor(c(1, 2, 3, 4))
variety <- as.factor(c("R", "F"))

                     
# data frame for our design 
mydesign <- tibble(plot = c((1:32), (1:32)),
                   season = c(rep(1, 32), rep(2, 32)), 
                   greenhouse = c(rep("A", 16), rep("B", 16), rep("A", 16), rep("B", 16)),
                   side = c(rep("n", 8), rep("s", 8), rep("n", 8), rep("s", 8), rep("n", 8), rep("s", 8), rep("n", 8), rep("s", 8))
                   
)

# assigning variety to greenhouse within season 

variety_assignment <- mydesign %>% 
  distinct(season, greenhouse) %>%
  group_by(season) %>%
  mutate(variety = sample(variety)) %>%
  ungroup()

# add variety assignments into design

mydesign <- mydesign %>% left_join(variety_assignment, by = c("season", "greenhouse"))

# randomise light and heat within greenhouse-side block

treats <- expand.grid(light = light, heat = heat)

mydesign <- mydesign %>%
  group_by(season, greenhouse) %>%
  mutate(
    temp_id = 1:16,
    treat = sample(1:16)
  ) %>%
  ungroup() %>%
  mutate(light = treats$light[treat],
         heat = treats$heat[treat]) %>%
  select(-temp_id, -treat)

```
